# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  fileSystems = {
    "/" = lib.mkForce {
      label = "NIXOS";
      fsType = "ext4";
    };

    "/boot" = {
      label = "${config.networking.hostName}-boot";
      fsType = "vfat";
    };

    "/home" = {
      label = "NIXHOME";
      fsType = "ext4";
    };

    # "/swap" = {
    #   label = config.networking.hostName;
    #   fsType = "btrfs";
    #   options = ["subvol=@swap" "noatime" "nodiratime" "discard=async"];
    # };

    # "/mnt/ruina" = {
    #   label = "ruina";
    #   fsType = "ntfs-3g";
    #   options = [ "rw" ];
    # };

    # "/mnt/ruina/boot" = {
    #   label = "ruinaboot";
    #   fsType = "vfat";
    # };
  };
in
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot = {
    initrd = {
      availableKernelModules = [
        "vmd"
        "xhci_pci"
        "ahci"
        "nvme"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];
      verbose = false;
    };

    # QEMU Hardware Acceleration
    kernelModules = [ "kvm-intel" ];

    # # OBS Loopback Camera
    # extraModulePackages = [ config.boot.kernelPackages.v4l2loopback ];
    # extraModprobeConfig = ''
    #   options v4l2loopback devices=1 video_nr=1 card_label="OBS Cam" exclusive_caps=1
    # '';

    # BTRFS Swap
    # resumeDevice = "/dev/disk/by-label/serena";
    # sudo btrfs inspect-internal map-swapfile /swap/swapfile -r
    # kernelParams = [ "resume_offset=533760" ];
  };

  inherit fileSystems;
  virtualisation.vmVariant = {
    # virtualisation.useDefaultFilesystems = false;
    virtualisation = {
      inherit fileSystems;
    };
  };

  # swapDevices = [ { device = "/swap/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;
  hardware.bluetooth.enable = true;

  hardware.keyboard.qmk.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
