;; try kakoune.el instead
;; update: it was very barebones
(use-package meow
  :preface
  (defun meow-setup ()
    (meow-motion-overwrite-define-key
     '("j" . meow-next)
     '("k" . meow-prev)
     '("<escape>" . keyboard-quit))

      (meow-leader-define-key
       '("w" . save-buffer)
       '("e" . project-eshell)
       '("f" . project-find-file)
       '("F" . find-file)
       '("b" . project-switch-to-buffer)
       '("B" . switch-to-buffer)
       '("p" . project-switch-project)
       '("k" . kill-buffer)
       '("K" . project-kill-buffers)
       '("o" . other-window)
       '("O" . delete-window))

    (meow-normal-define-key
     '(";" . meow-reverse)
     '("," . meow-inner-of-thing)
     '("." . meow-bounds-of-thing)
     '("[" . meow-beginning-of-thing)
     '("]" . meow-end-of-thing)
     '("a" . meow-append)
     '("o" . meow-open-below)
     '("b" . meow-back-word)
     '("B" . meow-back-symbol)
     '("c" . meow-change)
     '("d" . meow-delete)
     '("w" . meow-next-word)
     '("E" . meow-next-symbol)
     '("f" . meow-find)
     '("g" . meow-cancel-selection)
     '("G" . meow-grab)
     '("h" . meow-left)
     '("H" . meow-left-expand)
     '("i" . meow-insert)
     '("O" . meow-open-above)
     '("j" . meow-next)
     '("J" . meow-next-expand)
     '("k" . meow-prev)
     '("K" . meow-prev-expand)
     '("l" . meow-right)
     '("L" . meow-right-expand)
     '("m" . meow-join)
     '("n" . meow-search)
     '("M-o" . meow-block)
     '("M-O" . meow-to-block)
     '("p" . meow-yank)
     ;; '("q" . meow-quit)
     '("Q" . meow-goto-line)
     '("r" . meow-replace)
     '("R" . meow-swap-grab)
     '("s" . meow-kill)
     '("t" . meow-till)
     '("u" . meow-undo)
     '("U" . meow-undo-in-selection)
     '("/" . meow-visit)
     '("e" . meow-mark-word)
     '("W" . meow-mark-symbol)
     '("x" . meow-line)
     '("X" . meow-goto-line)
     '("y" . meow-save)
     '("Y" . meow-sync-grab)
     '("z" . meow-pop-selection)
     '("'" . repeat)
     '("<backspace>" . meow-left)
     '("<escape>" . keyboard-quit)))
  :config
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (setq meow-use-clipboard t)
  (setq meow-expand-hint-counts '((word . 0) (line . 0) (block . 0) (find . 0) (till . 0)))
  (meow-setup)
  (meow-global-mode 1))
